name: Push WaniKani random to TRMNL

on:
  schedule:
    # Runs every 4 hours at minute 7 (UTC)
    - cron: "7 */4 * * *"
  workflow_dispatch: {}   # allow manual runs
  
permissions:
  contents: read

jobs:
  run-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run script
        env:
          WANIKANI_API_TOKEN: ${{ secrets.WANIKANI_API_TOKEN }}
          TRMNL_WEBHOOK_URL: ${{ secrets.TRMNL_WEBHOOK_URL }}
        run: node wanikani_trmnl_random.js
